# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Radar_Filter/Radar_Filter.cache/wt} [current_project]
set_property parent.project_path {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Radar_Filter/Radar_Filter.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Radar_Filter/Radar_Filter.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/BCD_decoder/BCD_decoder.srcs/sources_1/new/BCD_decoder.vhd}
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Comparator_6bit/Comparator_6bit.srcs/sources_1/new/Comparator_6bit.vhd}
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Bubble_Sort/Bubble_Sort.srcs/sources_1/new/Bubble_Sort.vhd}
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Debounce/Debounce.srcs/sources_1/new/Debounce.vhd}
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/SevenSeg_display/SevenSeg_display.srcs/sources_1/new/SevenSeg_display.vhd}
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/FSM_7segment/FSM_7segment.srcs/sources_1/new/FSM_7segment.vhd}
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/LSFR_RNG_6bit/LSFR_RNG_6bit.srcs/sources_1/new/LSFR_RNG_6bit.vhd}
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/MedianFilter_FSM/MedianFilter_FSM.srcs/sources_1/new/MedianFilter_FSM.vhd}
  {C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Radar_Filter/Radar_Filter.srcs/sources_1/new/Radar_Filter.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Radar_Filter/Arty-S7-50-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/hardi/Documents/ELEC3356-01 Digital Systems/Projects/Radar Filter Final Project/Radar_Filter/Arty-S7-50-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Radar_Filter -part xc7s50csga324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Radar_Filter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Radar_Filter_utilization_synth.rpt -pb Radar_Filter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
